"""inkfox.memory submodule type stubs"""
from __future__ import annotations
from typing import Any, Mapping, Sequence

class PyMetadataIndex:
    def __init__(self, path: str | None = None) -> None: ...
    def batch_add(self, entries: Sequence[Mapping[str, Any]]) -> int: ...
    def search_flexible(self, params: Mapping[str, Any]) -> list[str]: ...
    def search_strict(self, params: Mapping[str, Any]) -> list[str]: ...
    def stats(self) -> dict[str, int]: ...
    def save(self) -> bool: ...

__all__ = ["PyMetadataIndex"]
